### ISSUE TITLE
"Permanently" set directories

### ISSUE THREAD

**Issue by cgrdn** [ArgoCanada/bgcArgoDMQC#38]
As I work with the package more operationally, I am getting frustrated with having to set my directories each time, even though it is just a copy/paste, I'd like to not have to do it all them time since my Argo data doesn't really move around. 

Thinking of some kind of `bgc.setup(argo_path='/my/argo/path/')` that would permanently save the path somewhere within the locally save bgcArgoDMQC module, which would then be overridden by calling `bgc.set_dirs()` in a given script.

**Comment by richardsc** [comment]
I'm no help for how to do this in python, but we have been having the exact same discussion over at [ArgoCanada/argoFloats](https://github.com/ArgoCanada/argoFloats/pull/307).

Ping us if you want some ideas :)

**Comment by cgrdn** [comment]
Thanks Clark, I do think there is something analogous I can do in python by shipping a .config file with the package. I'm just a little out of my depth in terms of how to properly do that so need to do a little research.

**Comment by cgrdn** [comment]
Done in 0c94c17.
